title: Bruce He # your name (or website title) here
#logo: "" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  3rd Year Software Engineering Student at the University of Waterloo.
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here